### PR TITLE
update `getIOSDevices` with slight better reporting #72

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/ci/73)

### CODE REVIEW

**Comment by larryonoff** [comment]
@yaronyg please review

**Comment by yaronyg** [comment]
Shouldn't this to be vNext and not master? Otherwise :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/73#-:-KRV1AeBuyiMs96Af3BX:b-c24g05)_

**Comment by larryonoff** [comment]
@yaronyg this's PR for CI. So there isn't vNext branch, only master.

**Comment by larryonoff** [comment]
@yaronyg I've merged this PR.

**Pull request merged**
