### PR TITLE
update CI

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/ci/83)

### CODE REVIEW

**Comment by larryonoff** [comment]
@mlesnic @czyzm @jareksl @yaronyg I just collected the changes (not all) on CI that weren't committed and created PR for this. Please review this PR.

**Comment by czyzm** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[tasker/check_node.sh, line 1 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KVixB5pMPmtYS2bjz-S:-KVixB5qs6OuZD60UjCa:bwigloo) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/tasker/check_node.sh#L1)):_

> ``` Shell
> #!/usr/bin/env bash
> ```

This and the next one are the files added long long time ago by Ville to help with diagnostic of nodes and connected devices. I think it is good to have them in repo.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by czyzm** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[builder/build__.sh, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KViyVB-r-yCrQSVy1lw:-KViyVB-r-yCrQSVy1lx:bj00dk8) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/build__.sh#L30)):_

> ``` Shell
> cd Github;ERROR_ABORT
> rm -rf testBuild;ERROR_ABORT
> cp -r testBuildOrg/ testBuild;
> ```

Wondering why ERROR_ABORT was removed from this item. I would try keeping it and run some build.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KVj-cBqKCPzxmepK_h4:-KVj-cBqKCPzxmepK_h5:b4ihhrc) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/virtual.js#L93)):_

> ``` JavaScript
>     data = data.replace("{{BUILD_SCRIPT_PATH}}", scr);
> 
>     if (job.test) {
> ```

This is some leftover from CI smoke tests. I don't see it is used anywhere so remove it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by czyzm** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[builder/build__.sh, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KViyVB-r-yCrQSVy1lw:-KVj4dEM6IhjmApWydWg:b-1qj0bi) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/build__.sh#L30)):_
<details><summary>

<i>Previously, czyzm wrote…</i></summary>



> Wondering why ERROR_ABORT was removed from this item. I would try keeping it and run some build.
> </details>
> let's wait what @mlesnic tells.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KVj-cBqKCPzxmepK_h4:-KVj4Z5u7jPBlv5EwucK:b-1qj0bi) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, czyzm wrote…</i></summary>



> This is some leftover from CI smoke tests. I don't see it is used anywhere so remove it.
> </details>
> let's wait what @mlesnic tells.

---

_[tasker/check_node.sh, line 1 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KVixB5pMPmtYS2bjz-S:-KVj4bsiWx0kimVmHO6N:b-896fix) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/tasker/check_node.sh#L1)):_
<details><summary>

<i>Previously, czyzm wrote…</i></summary>



> This and the next one are the files added long long time ago by Ville to help with diagnostic of nodes and connected devices. I think it is good to have them in repo.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[builder/build__.sh, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KViyVB-r-yCrQSVy1lw:-KVj4gNAraH9je8W1nF9:boemm19) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/build__.sh#L30)):_
<details><summary>

<i>Previously, larryonoff (larryonoff) wrote…</i></summary>



> let's wait what @mlesnic tells.
> </details>
> I agree that it's strange removing this check.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by yaronyg** [comment]
:lgtm: Obviously my lgtm isn't worth as much as the Rockwell folks.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[builder/build__.sh, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KViyVB-r-yCrQSVy1lw:-KVkbRgmqrLmaQscLeVd:b-4rv72x) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/build__.sh#L30)):_
<details><summary>

<i>Previously, larryonoff (larryonoff) wrote…</i></summary>



> I agree that it's strange removing this check.
> </details>
> Rather than using ERROR_ABORT everywhere I suggest instead using 'set -euo pipefail'. That will catch any error in any situation and make things fail. And it doesn't require peppering everything with ';ERROR_ABORT'. I would suggest however also adding https://github.com/thaliproject/Thali_CordovaPlugin/blob/iOS/build.sh#L16-L26 which will give you a nice output with which command failed. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83#-:-KVkc5jKYW2kKmPIXt9c:b-ila044)_

**Comment by lesn1kk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[builder/build__.sh, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KViyVB-r-yCrQSVy1lw:-KVxgO8A1-0dzFUPap1z:b6altfx) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/build__.sh#L30)):_
<details><summary>

<i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>



> Rather than using ERROR_ABORT everywhere I suggest instead using 'set -euo pipefail'. That will catch any error in any situation and make things fail. And it doesn't require peppering everything with ';ERROR_ABORT'. I would suggest however also adding https://github.com/thaliproject/Thali_CordovaPlugin/blob/iOS/build.sh#L16-L26 which will give you a nice output with which command failed. 
> </details>
> This was removed due to some problem with builds in the past. I believe it was something with permissions, like what I did lately. Current snapshot should be ok so we can bring ERROR_ABORT back.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KVj-cBqKCPzxmepK_h4:-KVxgi72VXDJaMx1wc3Y:b-rnvqav) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, larryonoff (larryonoff) wrote…</i></summary>



> let's wait what @mlesnic tells.
> </details>
> Yes, please remove it. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by larryonoff** [comment]
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

_[builder/build__.sh, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KViyVB-r-yCrQSVy1lw:-KW216YyqW5ItiWBqlgx:bevzttm) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/build__.sh#L30)):_
<details><summary>

<i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary>



> This was removed due to some problem with builds in the past. I believe it was something with permissions, like what I did lately. Current snapshot should be ok so we can bring ERROR_ABORT back.
> </details>
> I've migrated all shell scripts out of `ERROR_ABORT`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by larryonoff** [comment]
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/83#-KVj-cBqKCPzxmepK_h4:-KW21XWrSS6BsfUDUPtK:b-896fix) ([raw file](https://github.com/thaliproject/ci/blob/68de9f7629a95d6044a3dfbaf96bb4ce31a5663f/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary>



> Yes, please remove it. 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83)_

**Comment by larryonoff** [comment]
@czyzm @mlesnic please review updated PR.

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/83#-:-KW2deeAsONy6OciZ25c:bnfp4nl)_

**Pull request merged**
