### PR TITLE
implement CI doesn't replace all substitution variables for it's scripts

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/ci/85)

### CODE REVIEW

**Comment by larryonoff** [comment]
please review

**Comment by czyzm** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/85#-KViqYyk8zt2NO-E7vfi:-KViqYyl5-KBuN8GvTwv:b-5bpqh6) ([raw file](https://github.com/thaliproject/ci/blob/e79eb1c561256529294bb86393b3f5b2c1793dc6/builder/virtual.js#L93)):_

> ``` JavaScript
>     TARGET_BRANCH: job.targetBranch,
>     BUILD_SCRIPT_PATH: scr,
>     BUILD_SCRIPT: job.test ? scr + ' true' : scr,
> ```

Is this 'true' param used somehow?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85)_

**Comment by larryonoff** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/85#-KViqYyk8zt2NO-E7vfi:-KVirgGGjgAW3_o3G4df:b9px1nx) ([raw file](https://github.com/thaliproject/ci/blob/e79eb1c561256529294bb86393b3f5b2c1793dc6/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, czyzm wrote…</i></summary>



> Is this 'true' param used somehow?
> </details>
> This's a good question. I assume it was introduced for CI test mode by @mlesnic 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85)_

**Comment by czyzm** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/85#-KViqYyk8zt2NO-E7vfi:-KVj09OuXq1GwkEZZuVB:b-gyip0x) ([raw file](https://github.com/thaliproject/ci/blob/e79eb1c561256529294bb86393b3f5b2c1793dc6/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, larryonoff (larryonoff) wrote…</i></summary>



> This's a good question. I assume it was introduced for CI test mode by @mlesnic 
> </details>
> Look at the comment in #83 review - I think it should be removed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85)_

**Comment by czyzm** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85)_

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85#-:-KVkbBe_nshqb_kEFXrj:bnfp4nl)_

**Comment by yaronyg** [comment]
But my LGTM isn't worth as much as Rockwell's so please go with their approval.

**Comment by lesn1kk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/85#-KViqYyk8zt2NO-E7vfi:-KVxhQIahGia8VGvNXzV:bi6ougo) ([raw file](https://github.com/thaliproject/ci/blob/e79eb1c561256529294bb86393b3f5b2c1793dc6/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, czyzm wrote…</i></summary>



> Look at the comment in #83 review - I think it should be removed.
> </details>
> Please remove it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85)_

**Comment by larryonoff** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[builder/virtual.js, line 93 at r1](https://reviewable.io:443/reviews/thaliproject/ci/85#-KViqYyk8zt2NO-E7vfi:-KW22VHIECjGx5BmoUMT:b-896fix) ([raw file](https://github.com/thaliproject/ci/blob/e79eb1c561256529294bb86393b3f5b2c1793dc6/builder/virtual.js#L93)):_
<details><summary>

<i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary>



> Please remove it.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85)_

**Comment by larryonoff** [comment]
@mlesnic @czyzm please review updated PR

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/ci/85#-:-KW2cZHZ9-bjZ1Uie3Fa:bnfp4nl)_

**Pull request merged**
